### PR TITLE
fix: Handle SIGINT, SIGTERM, & SIGHUP gracefully

### LINKED ISSUE #738: Non-zero exit code in response to SIGTERM
### bug

`ganache-cli` does respond to sigterm and shutsdown, but does so with a failure exit code.
since the shutdown happened cleanly, it should exit with a zero error code. this is useful in tests that rely on exit codes detect failures.

### reproduction

start ganache cli
```bash
npx ganache-cli
```
in another terminal
```
# get ganache pid via port usage
lsof -ti:8545
# send SIGTERM (15) to ganache PID
kill -15 $(lsof -ti:8545)
```
back in the other terminal
```
# get exit code of previous command
echo $?
143
```

### PR DESCRIPTION
**Pull request by nicholasjpaterno**
Only exit with code 0 when gracefully exiting.

Fixes #738

### CODE REVIEW

**Review by nicholasjpaterno — COMMENTED** [review]
Related to #738

**Review by davidmurdoch — APPROVED** [review]
LGTM!

File: cli.js [hunk 1]
```diff
@@ -205,15 +205,29 @@ if (process.platform === "win32") {
   })
   .on("SIGINT", function () {
     process.emit("SIGINT");
+  })
+  .on("SIGHUP", function () {
+    process.emit("SIGHUP");
```
Comment (davidmurdoch) [inline cli.js]: Remove this. It isn't needed.

**Review by davidmurdoch — CHANGES_REQUESTED** [review]

**Review by davidmurdoch — APPROVED** [review]
